=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1005/kszb_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="konyvek">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="konyv" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="cim" type="xs:string" />
							<xs:element name="kiadasi_ev" type="xs:unsignedShort" />
							<xs:element name="kiado" type="xs:string" />
							<xs:element name="szerzo" type="xs:string" maxOccurs="unbounded" />
							<xs:element name="absztrakt" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="kod" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1005/kszb_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE konyvek SYSTEM "kszb_konyv.dtd">-->
<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kszb_konyv.xsd">
	<konyv kod="x01">
		<cim>Computer Networks (5th Edition)</cim>
		<kiadasi_ev>2010</kiadasi_ev>
		<kiado>Pearson</kiado>
		<szerzo>Andrew Tanenbaum</szerzo>
		<szerzo>David Wetherall</szerzo>
		<absztrakt>Computer Networks, 5/e is appropriate for Computer Networking or Introduction to Networking courses at both the undergraduate and graduate level in Computer Science, Electrical Engineering, CIS, MIS, and Business Departments.</absztrakt>
	</konyv>
	<konyv kod="x02">
		<cim>Databases and Algorithms in Java 2nd edition</cim>
		<kiadasi_ev>2002</kiadasi_ev>
		<kiado>Sams Publishing</kiado>
		<szerzo>Robert Lafore</szerzo>
		<absztrakt>Data Structures and Algorithms in Java, Second Edition is designed to be easy to read and understand although the topic itself is complicated.</absztrakt>
	</konyv>
	<konyv kod="x03">
		<cim>Assembly Language Primer for the IBM PC</cim>
		<kiadasi_ev>1984</kiadasi_ev>
		<kiado>Plume</kiado>
		<szerzo>Robert Lafore</szerzo>
		<absztrakt>Explains how assembly language works, discusses sound generation, memory segmentation, color graphics, and language interfaces, and shows how to write programs in assembly language</absztrakt>
	</konyv>
</konyvek>
