=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1012/kszb_orarend1.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="orarend">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ora" type="oraTipus" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>	
	</xs:element>
	
	<xs:complexType name="oraTipus">
		<xs:sequence>
			<xs:element name="targy" type="xs:string"/>
			<xs:element name="idopont" type="idopontTipus"/>
			<xs:element name="helyszin" type="xs:string"/>
			<xs:element name="oktato" type="xs:string"/>
			<xs:element name="szak" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="kod" type="xs:string" use="required"/>
		<xs:attribute name="tipus" type="oraTipusTipus" use="required" />
	</xs:complexType>
	
	<xs:simpleType name="oraTipusTipus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="eloadas"/>
			<xs:enumeration value="gyakorlat"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="idopontTipus">
		<xs:sequence>
			<xs:element name="nap" type="xs:string"/>
			<xs:element name="tol" type="xs:integer"/>
			<xs:element name="ig" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1012/kszb_orarend1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- <!DOCTYPE orarend SYSTEM "SD_orarend.dtd"> -->
<orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kszb_orarend1.xsd">
	<ora kod="01" tipus="eloadas">
		<targy>WEB technológiák 1</targy>
		<idopont>
			<nap>Hetfo</nap>
			<tol>12</tol>
			<ig>14</ig>
		</idopont>
		<helyszin>A1 305</helyszin>
		<oktato>Agárdi Anita</oktato>
		<szak>Programtervezo informatikus</szak>
	</ora>
	<ora kod="02" tipus="eloadas">
		<targy>Mesterseges inteligencia alapjai</targy>
		<idopont>
			<nap>Hetfo</nap>
			<tol>14</tol>
			<ig>17</ig>
		</idopont>
		<helyszin>XXXII eloado</helyszin>
		<oktato>Dr. Dudás László</oktato>
		<szak>Mernök info.</szak>
	</ora>
	<ora kod="03" tipus="eloadas">
		<targy>Adatkezelés XML-ben</targy>
		<idopont>
			<nap>Kedd</nap>
			<tol>12</tol>
			<ig>14</ig>
		</idopont>
		<helyszin>I A2 fsz.</helyszin>
		<oktato>Dr. Bendarik László</oktato>
		<szak>Programtervezo informatikus</szak>
	</ora>
	<ora kod="04" tipus="gyakorlat">
		<targy>Adatkezelés XML-ben</targy>
		<idopont>
			<nap>Kedd</nap>
			<tol>14</tol>
			<ig>16</ig>
		</idopont>
		<helyszin>In/103 In I. em. 103</helyszin>
		<oktato>Dr. Bendarik László</oktato>
		<szak>Programtervezo informatikus</szak>
	</ora>
	<ora kod="05" tipus="gyakorlat">
		<targy>WEB technológiák 1</targy>
		<idopont>
			<nap>Kedd</nap>
			<tol>16</tol>
			<ig>18</ig>
		</idopont>
		<helyszin>In/103 In I. em. 103</helyszin>
		<oktato>Agárdi Anita</oktato>
		<szak>Programtervezo informatikus</szak>
	</ora>
	<ora kod="06" tipus="gyakorlat">
		<targy>Mesterseges inteligencia alapjai</targy>
		<idopont>
			<nap>Kedd</nap>
			<tol>18</tol>
			<ig>19</ig>
		</idopont>
		<helyszin>inf. 15</helyszin>
		<oktato>Dr. Dudás László</oktato>
		<szak>Programtervezo informatikus</szak>
	</ora>
</orarend>
