=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1012/kszb_nevjegykartya.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="nevjegykartyak">
		<xs:complexType>
			<xs:sequence minOccurs="2" maxOccurs="unbounded">
				<xs:element name="nevjegykartya" type="nevjegykartyaTipus"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="nevjegykartyaTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="ceg" type="cegTipus"/>
			<xs:element name="beosztas" type="xs:string"/>
			<xs:element name="telefonszam" type="xs:string"/>
			<xs:element name="email" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="cegTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="cim" type="cimTipus"/>
			<xs:element name="telefonszam" type="xs:string"/>
			<xs:element name="weblap" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="cimTipus">
		<xs:sequence>
			<xs:element name="iranyitoszam" type="xs:integer"/>
			<xs:element name="varos" type="xs:string"/>
			<xs:element name="utca" type="xs:string"/>
			<xs:element name="hazszam" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1012/kszb_nevjegykartya.xml
<?xml version="1.0" encoding="utf-8"?>
<nevjegykartyak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kszb_nevjegykartya.xsd">
	<nevjegykartya id="1">
		<nev>Bajusz Istvan</nev>
		<ceg>
			<nev>Miskolci Egyetem</nev>
			<cim>
				<iranyitoszam>3515</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Egyetemvaros</utca>
				<hazszam>654</hazszam>
			</cim>
			<telefonszam>06702589634</telefonszam>
			<weblap>http://www.uni-miskolc.hu/</weblap>
		</ceg>
		<beosztas>hallgat√≥</beosztas>
		<telefonszam>123456789</telefonszam>
		<email>bajuszistvn@gmail.com</email>
	</nevjegykartya>
	<nevjegykartya id="2">
		<nev>Kovacs Bela</nev>
		<ceg>
			<nev>Miskolci Egyetem</nev>
			<cim>
				<iranyitoszam>3515</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Egyetemvaros</utca>
				<hazszam>98</hazszam>
			</cim>
			<telefonszam>06307894561</telefonszam>
			<weblap>https://www.dsadas.com</weblap>
		</ceg>
		<beosztas>Asd</beosztas>
		<telefonszam>987654321</telefonszam>
		<email>asd@gmail.com</email>
	</nevjegykartya>
</nevjegykartyak>
