=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1026/src/domh46lpd/usersh46lpd.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" minOccurs="3" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firstname" type="xs:string"/>
							<xs:element name="lastname" type="xs:string"/>
							<xs:element name="profession" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedShort" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_1026/bin/domh46lpd/usersh46lpd.xml
<?xml version="1.0" encoding="utf-8"?>

<users><!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="usersh46lpd.xsd"> --> 
	<user id="1">
		<firstname>Istvan</firstname>
		<lastname>Bajusz</lastname>
		<profession>student</profession>
	</user>
	<user id="2">
		<firstname>Bela</firstname>
		<lastname>Kovacs</lastname>
		<profession>cashier</profession>
	</user>
	<user id="3">
		<firstname>Laszlo</firstname>
		<lastname>Nagy</lastname>
		<profession>asd</profession>
	</user>
</users>
