=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_0928/kszb_ertodtd.dtd
<!ELEMENT er (A*, B* ,C*, A_B*)>
<!ELEMENT A (Ab*, Ac)>
<!ATTLIST A Aa ID #REQUIRED>
<!ELEMENT Ab (Abx, Aby)>
<!ELEMENT Abx (#PCDATA)>
<!ELEMENT Aby (#PCDATA)>
<!ELEMENT Ac (Acd, Ace)>
<!ELEMENT Acd (#PCDATA)>
<!ELEMENT Ace (#PCDATA)>
<!ELEMENT B (Bb)>
<!ATTLIST B Ba ID #REQUIRED>
<!ATTLIST B Bc IDREF #IMPLIED>
<!ELEMENT Bb (Bbx, Bby)>
<!ELEMENT Bbx (#PCDATA)>
<!ELEMENT Bby (#PCDATA)>
<!ELEMENT C (Cb)>
<!ATTLIST C Ca ID #REQUIRED>
<!ELEMENT Cb (#PCDATA)>
<!ELEMENT A_B (A_Bc)>
<!ATTLIST A_B A_B_a IDREF #IMPLIED>
<!ATTLIST A_B A_B_b IDREF #IMPLIED>
<!ELEMENT A_Bc (#PCDATA)>

=== klaben-szabolcs-bence/h46lpd_xmlgyak/h46lpd_0928/kszb_dtdtoxml.xml
<?xml version="1.0"?>

<!DOCTYPE er SYSTEM "kszb_ertodtd.dtd">
<er>
    <A Aa="a_0">
        <Ab>
            <Abx></Abx>
            <Aby></Aby>
        </Ab>
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <B Ba="b_0" Bc="c_0">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="c_0">
        <Cb></Cb>
    </C>
    <A_B A_B_a="a_0" A_B_b="b_0">
        <A_Bc></A_Bc>
    </A_B>
</er>
